### ISSUE TITLE
Invite your POSTER for our pre-heat for the CVPR offline conference in Seattle

### ISSUE THREAD

**Issue by autodriving-heart** [Windsrain/Selective-Stereo#10]
We sincerely look forward to your poster and will arrange a collection (will show on bilibili)for all authors as a pre-heat for the offline conference. It is  convenient for everyone to discuss the posters in advance and this will be a period of significant memory for everyone. You can also send us the exhibition information with poster.

Our email ：autodrivingtech@163.com
WeChat：AIDriver002

**Comment by Windsrain** [comment]
The poster has been sent. Thanks for your invitation.

**Comment by autodriving-heart** [comment]
Here's the pre-heat video link：
【太亮眼！CVPR 2024 自动驾驶方向中稿论文POSTER大全！】 https://www.bilibili.com/video/BV1bf421B7E9/?share_source=copy_web&vd_source=d87a196e6f29032f5720781b25389bc7
 And, we sincerely hope to invite your team to join in a live broadcast. Look forward to your reply!
