### ISSUE TITLE
About Middleburry checkpoints

### ISSUE THREAD

**Issue by Guptajakala** [Windsrain/Selective-Stereo#12]
what's the difference between `middlebury_train.pth` and `middlebury_finetune.pth`? How are they obtained respectively?

**Comment by Windsrain** [comment]
See Middlebury of Sec 4.3 in the paper.

**Comment by Guptajakala** [comment]
"we first finetune the Scene Flow pretrained model on the mixed Tartan Air [28], CREStereo Dataset [15], Scene Flow [19], Falling Things [27], InStereo2k [2], CARLA HR-VS [39] and Middlebury [22] datasets using a crop size of 384×512 for 200k steps" this is `middlebury_train.pth`

"Then we finetune it on the mixed CREStereo Dataset [15], Falling Things [27], InStereo2k [2], CARLA HR-VS [39] and Middlebury [22] datasets using a crop size of 384 × 768 with a batch size of 8 for another 100k steps" this is `middlebury_finetune.pth`

is that right?

**Comment by Windsrain** [comment]
Right.

**Comment by Guptajakala** [comment]
thank you!
