### ISSUE TITLE
关于论文中Middlebury训练的问题

### ISSUE THREAD

**Issue by iaphantom** [Windsrain/Selective-Stereo#15]
请问下训练Middlebury数据集的时候，除了MiddEval3明确了分辨率，比如2005和2006，使用的full还是half分辨率的数据集？

**Comment by Windsrain** [comment]
请看stereo_datasets.py的fetch_dataloader部分，构建数据集时明确了分辨率是多少，默认是F。

**Comment by iaphantom** [comment]
非常感谢
