### ISSUE TITLE
-

### ISSUE THREAD

**Issue by 1434205229** [Windsrain/Selective-Stereo#16]

**Comment by Windsrain** [comment]
评估代码其实很简单，就是用opencv-python的cv2.canny函数做的边缘检测分割
&nbsp;


奇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月30日(星期二) 上午10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Windsrain/Selective-Stereo] 作者您好，请问您是如何进行不同区域sceneflow测试集的定量评估的？ (Issue #16)














 
“To validate the ability to fuse information by regions of our modules, we then split Scene Flow test set into two regions: edge regions and non-edge regions using the Canny operator.”
 ***@***.***

**Comment by 1434205229** [comment]
好的谢谢您
