### ISSUE TITLE
关于kitti模型训练的问题

### ISSUE THREAD

**Issue by zjyaccount** [Windsrain/Selective-Stereo#19]
作者您好，根据代码和论文中的描述，用于kitti12和kitti15推理的模型为同一个模型，都是在kitti12和kitti15的混合数据集上训练得到的。但是google drive里面给出的模型中，kitti12和kitti15的模型是分开提供的，是否可以理解为这两个模型的权重是完全一致的，还是有更多其他的训练细节呢？

**Comment by Windsrain** [comment]
https://github.com/Windsrain/Selective-Stereo/issues/5
可以看一下这个issue

**Comment by zjyaccount** [comment]
> #5 可以看一下这个issue

感谢！
