### ISSUE TITLE
KITTI 2012 reflective regions

### ISSUE THREAD

**Issue by Guptajakala** [Windsrain/Selective-Stereo#20]
Hi, congrats on the great work! In your paper appendix, there is a evaluation on "KITTI 2012 reflective regions". Where can I get it? I didn't find it on the KITTI website.

**Comment by Windsrain** [comment]
See in here: https://www.cvlibs.net/datasets/kitti/eval_stereo_flow.php?benchmark=stereo&table=refl&error=3&eval=all

**Comment by Guptajakala** [comment]
@Windsrain , is "KITTI 2012 reflective regions" the same thing as KITTI 2012? I thought there is another subset for "reflective regions".

**Comment by Windsrain** [comment]
![24dd22c58868f3fc3177214cd73ecca4](https://github.com/user-attachments/assets/26fbc493-3a90-4d98-84fe-fcb12524c659)
Actually, KITTI 2012 benchmark has this subset table.

**Comment by Guptajakala** [comment]
thank you a lot!!
