### ISSUE TITLE
Thank you. The work of the paper has been reproduced, and there is a noticeable improvement in performance. 

### ISSUE THREAD

**Issue by np-csu** [Windsrain/Selective-Stereo#3]
The area that requires time is the tuning of the kernel of small gru and large gru.

**Comment by drilistbox** [comment]
Can you release the code for study?

**Comment by np-csu** [comment]
> Can you release the code for study?

Sorry I cannot. But follow the paper, you can implemente the code in half day.

**Comment by Windsrain** [comment]
> Can you release the code for study?

I have uploaded the initial code, and you can view the core code of the module. IGEV-version, checkpoints and README will be updated soon.

**Comment by S1aoXuan** [comment]
> The area that requires time is the tuning of the kernel of small gru and large gru.

Can you show the training curve please? It's the **scene-flow-epe** part of the tensorboard, and my curves are dropping very slowly, so I don't know if there's a problem.
