### ISSUE TITLE
Pretrained Selective-IGEV

### ISSUE THREAD

**Issue by nhanerc** [Windsrain/Selective-Stereo#6]
Thanks for such a simple but effective approach.

I see you share pre-trained weights of Selective RAFT, can you also share pre-trained weights of Selective IGEV for comparison purposes?

**Comment by Windsrain** [comment]
Sure, but I've been a bit busy lately and it may take some time before I can publish.

**Comment by Windsrain** [comment]
All checkpoints have been published in Google Drive.
