### ISSUE TITLE
关于scene flow数据集训练问题

### ISSUE THREAD

**Issue by S1aoXuan** [Windsrain/Selective-Stereo#7]
作者您好，我想问问您在您的实验环境中训练大概用了几天时间呢？
方便贴出您训练selective-IGEV时的**scene-flow-epe**的训练曲线吗？

**Comment by Windsrain** [comment]
3天。
![LVN83}S JO} 27Q3)2DXVUV](https://github.com/Windsrain/Selective-Stereo/assets/43723173/9ec609d7-c74c-4aa5-ac6b-cdf74c271d87)

**Comment by S1aoXuan** [comment]
非常感谢您！！

**Comment by S1aoXuan** [comment]
作者您好，我用您的代码在我的电脑上跑了20k，目前的结果跟您的差距很大，EPE几乎是您的2倍了，是不是配置的环境有问题。
![image](https://github.com/Windsrain/Selective-Stereo/assets/92132890/b9beb31a-6e84-47c6-964e-4c1f4adefe19)
我的环境是pytorch1.13.1 cuda11.7

**Comment by Windsrain** [comment]
检查timm版本是不是0.5.4，所有参数是不是都没改，训练集数量是不是35454

**Comment by S1aoXuan** [comment]
是的，我直接git下来然后换了自己的数据集路径
奇怪的是，我用这个环境直接跑IGEV-Stereo是没有问题的

**Comment by Windsrain** [comment]
你的问题我没出现过，你可尝试把源码里我的模块先注释掉，这样就相当于IGEV，跑一下看看有没有问题

**Comment by S1aoXuan** [comment]
好的，我试一试

**Comment by Windsrain** [comment]
看看你的tensorboard里1px曲线在20k是多少

**Comment by S1aoXuan** [comment]
0.6849

**Comment by Windsrain** [comment]
这个太低了，我这边10k有0.83。得看看预训练backbone有没有加载上

**Comment by S1aoXuan** [comment]
这个该如何查看呢？代码最开始运行的时候有提示Loading pretrained weights from url

**Comment by Windsrain** [comment]
因为上传到github的代码我目前还没有多余的卡去重新训练检查，我建议你先把我的模块代码复制到你运行正常的IGEV里，等我之后放出正式版本。

**Comment by S1aoXuan** [comment]
好的

**Comment by Windsrain** [comment]
我这边检查过了，github上的Selective-IGEV确实训练有问题，稍后我会重新提交一个版本。

**Comment by Windsrain** [comment]
问题已定位在Selective-IGEV/core/stereo_datasets.py第81行，把-disp改成disp就行。因为Selective-RAFT沿用RAFT，所以用的是坐标差即负视差，但Selective-IGEV沿用IGEV，直接用disp就行。新版本已更新。

**Comment by S1aoXuan** [comment]
谢谢您，我目前是将您的模块插入到IGEV-Stereo中在运行，目前也是正常的
