### ISSUE TITLE
关于SceneFlow训练的问题

### ISSUE THREAD

**Issue by yxg19991231** [Windsrain/Selective-Stereo#8]
训练Selective-IGEV用两个3090就会爆显存，之前训练IGEV就没事，感觉参数量反而小了

**Comment by Windsrain** [comment]
Selective-IGEV参数量比IGEV大，而且SRU要维持两个GRU分支，2张3090默认配置确实不够，可以考虑降低train_iters至16，适当增加num_steps。

**Comment by yxg19991231** [comment]
降低train_iters和增加num_steps会影响最终训练的效果吧？如果单独用SRU，具体代码该如何改，我尝试改了下若没有CSA模块会报各种错误

**Comment by Windsrain** [comment]
1. 肯定会，只是做个权衡，既然训练次数不能到22次，那就只能延长训练时间了。
2. 单独用SRU效果达不到最佳，如果你只是想做消融实验，那就修改BasicSelectiveMultiUpdateBlock，在forward中去掉att参数，至于大小GRU的和，去掉att只能用平均值了
