### ISSUE TITLE
How much GPU memory do you need to run validation on Middlebury?

### ISSUE THREAD

**Issue by Guptajakala** [Windsrain/Selective-Stereo#9]
> When validating with Middlebury, set max_disp to 768 and set valid_iters to 80.

Did you run this on the full resolution, or half? How much memory do we need?

**Comment by Windsrain** [comment]
Yes, I run this on the full resolution. You can also try other resolutions. I forgot how much memory is needed for inference, but one 3090 is enough.

**Comment by Guptajakala** [comment]
Thanks!
